header = (/"18-22B 18-22P 19-23B 19-23P 20-24B 20-24P 21-25B 21-25P 22-26B 22-26P 23-27B 23-27P 24-28B 24-28P 25-29B 25-29P 26-30B 26-30P 27-31B 27-31P"/)
hlist = [/header/]
alist = [/pm25_sim_a1_subset,pm25_sim_b1_subset,pm25_sim_a2_subset,pm25_sim_b2_subset,pm25_sim_a3_subset,pm25_sim_b3_subset,pm25_sim_a4_subset,pm25_sim_b4_subset,pm25_sim_a5_subset,pm25_sim_b5_subset,pm25_sim_a6_subset,pm25_sim_b6_subset,pm25_sim_a7_subset,pm25_sim_b7_subset,pm25_sim_a8_subset,pm25_sim_b8_subset,pm25_sim_a9_subset,pm25_sim_b9_subset,pm25_sim_a10_subset,pm25_sim_b10_subset/]
print("alist created...now writing")
fname = "pm25_pulseruns_APEC2_Oct.txt"
write_table(fname, "w", hlist, "%s")
write_table(fname, "a", alist, "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f")

alist = [/pm10_sim_a1_subset,pm10_sim_b1_subset,pm10_sim_a2_subset,pm10_sim_b2_subset,pm10_sim_a3_subset,pm10_sim_b3_subset,pm10_sim_a4_subset,pm10_sim_b4_subset,pm10_sim_a5_subset,pm10_sim_b5_subset,pm10_sim_a6_subset,pm10_sim_b6_subset,pm10_sim_a7_subset,pm10_sim_b7_subset,pm10_sim_a8_subset,pm10_sim_b8_subset,pm10_sim_a9_subset,pm10_sim_b9_subset,pm10_sim_a10_subset,pm10_sim_b10_subset/]
print("alist created...now writing")
fname = "pm10_pulseruns_APEC2_Oct.txt"
write_table(fname, "w", hlist, "%s")
write_table(fname, "a", alist, "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f")

alist = [/co_sim_a1_subset,co_sim_b1_subset,co_sim_a2_subset,co_sim_b2_subset,co_sim_a3_subset,co_sim_b3_subset,co_sim_a4_subset,co_sim_b4_subset,co_sim_a5_subset,co_sim_b5_subset,co_sim_a6_subset,co_sim_b6_subset,co_sim_a7_subset,co_sim_b7_subset,co_sim_a8_subset,co_sim_b8_subset,co_sim_a9_subset,co_sim_b9_subset,co_sim_a10_subset,co_sim_b10_subset/]
print("alist created...now writing")
fname = "co_pulseruns_APEC2_Oct.txt"
write_table(fname, "w", hlist, "%s")
write_table(fname, "a", alist, "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f")

alist = [/no2_sim_a1_subset,no2_sim_b1_subset,no2_sim_a2_subset,no2_sim_b2_subset,no2_sim_a3_subset,no2_sim_b3_subset,no2_sim_a4_subset,no2_sim_b4_subset,no2_sim_a5_subset,no2_sim_b5_subset,no2_sim_a6_subset,no2_sim_b6_subset,no2_sim_a7_subset,no2_sim_b7_subset,no2_sim_a8_subset,no2_sim_b8_subset,no2_sim_a9_subset,no2_sim_b9_subset,no2_sim_a10_subset,no2_sim_b10_subset/]
print("alist created...now writing")
fname = "no2_pulseruns_APEC2_Oct.txt"
write_table(fname, "w", hlist, "%s")
write_table(fname, "a", alist, "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f")

alist = [/so2_sim_a1_subset,so2_sim_b1_subset,so2_sim_a2_subset,so2_sim_b2_subset,so2_sim_a3_subset,so2_sim_b3_subset,so2_sim_a4_subset,so2_sim_b4_subset,so2_sim_a5_subset,so2_sim_b5_subset,so2_sim_a6_subset,so2_sim_b6_subset,so2_sim_a7_subset,so2_sim_b7_subset,so2_sim_a8_subset,so2_sim_b8_subset,so2_sim_a9_subset,so2_sim_b9_subset,so2_sim_a10_subset,so2_sim_b10_subset/]
print("alist created...now writing")
fname = "so2_pulseruns_APEC2_Oct.txt"
write_table(fname, "w", hlist, "%s")
write_table(fname, "a", alist, "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f")

alist = [/o3_sim_a1_subset,o3_sim_b1_subset,o3_sim_a2_subset,o3_sim_b2_subset,o3_sim_a3_subset,o3_sim_b3_subset,o3_sim_a4_subset,o3_sim_b4_subset,o3_sim_a5_subset,o3_sim_b5_subset,o3_sim_a6_subset,o3_sim_b6_subset,o3_sim_a7_subset,o3_sim_b7_subset,o3_sim_a8_subset,o3_sim_b8_subset,o3_sim_a9_subset,o3_sim_b9_subset,o3_sim_a10_subset,o3_sim_b10_subset/]
print("alist created...now writing")
fname = "o3_pulseruns_APEC2_Oct.txt"
write_table(fname, "w", hlist, "%s")
write_table(fname, "a", alist, "%5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f %5.2f")

